<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8abf93cd-6bcc-40b1-86cf-d966e757f632</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate" Version="15.1.10" />
    <PackageReference Include="HotChocolate.Abstractions" Version="15.1.10" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="15.1.10" />
    <PackageReference Include="HotChocolate.Language" Version="15.1.10" />
    <PackageReference Include="HotChocolate.Language.Web" Version="15.1.10" />
    <PackageReference Include="HotChocolate.Server" Version="10.5.5" />
    <PackageReference Include="HotChocolate.Types" Version="15.1.10" />
    <PackageReference Include="HotChocolate.Utilities" Version="15.1.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
